[package]
name = "cropper"
version = "0.1.0"
edition = "2021"

[dependencies]
cairo-rs = { version = "0.20.7", features = ["png"] }
clap = { version = "4.5.23", features = ["derive"] }
regex = "1.11.1"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.134"
